version: "3"

services:
  mongo:
    image: mongo:4
    restart: always

backend:
  build: backend
  restart: always
  links:
    - mongo
  depends_on:
    - mongo
  environment:
    - PORT=5000
  ports:
    - 4242:3000

frontend:
  build: frontend
  restart: always
  depends_on:
    - backend
  environment:
    - NODE_ENV=production
    - REACT_APP_API_URL=https//kurentochat-fl/staging.forasoft.com
  ports:
  - 6969:3000

networks: 
  default:
    external:
     name: demoserver_network_1